// Event data sourced and paraphrased from FBLA's official 2025-2026
// Middle School & High School Competitive Events Guidelines (fbla.org).
// Each entry: slug, name, level, type, grades (optional), desc, skills, pdf

const FORMAT_INFO = {
  "Objective Test": {
    label: "Objective Test",
    blurb: "A proctored, multiple-choice knowledge test on the topic. There's no live presentation for this event — success comes down to studying the topic list and guidelines closely before competition day."
  },
  "Role Play": {
    label: "Role Play",
    blurb: "This event pairs an objective test with a live role-play scenario. Competitors are handed a business situation, given prep time, and then present their solution to a judge acting the part of a client, manager, or customer."
  },
  "Presentation": {
    label: "Presentation",
    blurb: "This event combines a pre-judged submission — a report, portfolio, script, or built project — with a live presentation delivered to a panel of judges."
  },
  "Production": {
    label: "Production Test",
    blurb: "A hands-on, timed test of real software skills, often paired with a short objective-test component graded separately."
  },
  "Chapter Event": {
    label: "Chapter Event",
    blurb: "A chapter-wide event prepared and presented by a team representing the whole chapter's work over the year, evaluated through a written report and a live presentation."
  }
};

const EVENTS = [
// ===== HIGH SCHOOL — OBJECTIVE TESTS =====
{slug:"accounting", name:"Accounting", level:"High School", type:"Objective Test", desc:"Tests understanding of core accounting principles — financial statements, journal entries, and the accounting cycle — as a starting point for exploring finance and accounting careers.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Accounting.pdf", chapterEvent:true},
{slug:"advanced-accounting", name:"Advanced Accounting", level:"High School", type:"Objective Test", desc:"A step up from Accounting, covering corporate accounting, managerial accounting, and financial analysis for members ready to go deeper into the field.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Advanced-Accounting.pdf"},
{slug:"advertising", name:"Advertising", level:"High School", type:"Objective Test", desc:"Covers media planning, branding, consumer behavior, and the promotional techniques companies use to reach target audiences.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Advertising.pdf"},
{slug:"agribusiness", name:"Agribusiness", level:"High School", type:"Objective Test", desc:"Applies business principles to the agriculture industry, spanning agricultural marketing, economics, finance, and supply chains.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Agribusiness.pdf"},
{slug:"business-communication", name:"Business Communication", level:"High School", type:"Objective Test", desc:"Covers written and verbal workplace communication, digital correspondence, and professional etiquette.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Business-Communication.pdf"},
{slug:"business-law", name:"Business Law", level:"High School", type:"Objective Test", desc:"Explores how the legal system shapes business — contracts, ethics, employment law, and consumer protection.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Business-Law.pdf"},
{slug:"computer-problem-solving", name:"Computer Problem Solving", level:"High School", type:"Objective Test", desc:"Tests knowledge of computer systems, operating systems, networking, and hardware troubleshooting.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Computer-Problem-Solving.pdf"},
{slug:"cybersecurity", name:"Cybersecurity", level:"High School", type:"Objective Test", desc:"Covers protecting systems and data from viruses, malware, phishing, and spyware, plus core cybersecurity best practices.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Cybersecurity.pdf"},
{slug:"data-science-and-ai", name:"Data Science & AI", level:"High School", type:"Objective Test", desc:"Introduces data analysis, machine learning, and artificial intelligence concepts and their role in solving real-world business problems.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Data-Science-and-AI.pdf"},
{slug:"economics", name:"Economics", level:"High School", type:"Objective Test", desc:"Covers supply and demand, market structures, fiscal and monetary policy, and how economic forces shape global markets.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Economics.pdf"},
{slug:"healthcare-administration", name:"Healthcare Administration", level:"High School", type:"Objective Test", desc:"Covers medical terminology, office procedures, and the administrative functions that keep a healthcare setting running smoothly.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Healthcare-Administration.pdf"},
{slug:"human-resource-management", name:"Human Resource Management", level:"High School", type:"Objective Test", desc:"Covers key HR functions — staffing, training, employee relations, and performance management — and how they support organizational success.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Human-Resource-Management.pdf", chapterEvent:true},
{slug:"insurance-and-risk-management", name:"Insurance & Risk Management", level:"High School", type:"Objective Test", desc:"Explores how individuals and businesses identify, assess, and mitigate risk through insurance products and strategic planning.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Insurance-and-Risk-Management.pdf"},
{slug:"intro-business-communication", name:"Introduction to Business Communication", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"An entry-level look at written and verbal communication, digital messaging, and professional etiquette for underclassmen.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Business-Communication.pdf"},
{slug:"intro-business-concepts", name:"Introduction to Business Concepts", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Introduces foundational business functions — management, marketing, finance, and operations — for members new to the field.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Business-Concepts.pdf"},
{slug:"intro-business-procedures", name:"Introduction to Business Procedures", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Covers basic office procedures, administrative tasks, and workplace protocols for underclassmen.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Business-Procedures.pdf"},
{slug:"intro-fbla", name:"Introduction to FBLA", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Tests knowledge of FBLA's own history, structure, programs, and leadership — a great way to learn the organization inside and out.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-FBLA.pdf"},
{slug:"intro-information-technology", name:"Introduction to Information Technology", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Covers computer systems, software, networks, and data management fundamentals for members newer to IT.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Information-Technology.pdf"},
{slug:"intro-marketing-concepts", name:"Introduction to Marketing Concepts", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Covers foundational marketing ideas — product promotion, pricing, consumer behavior, and how goods and services get sold.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Marketing-Concepts.pdf"},
{slug:"intro-parliamentary-procedure", name:"Introduction to Parliamentary Procedure", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Introduces the basic rules for running orderly, effective meetings — motions, voting, and meeting structure.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Parliamentary-Procedure.pdf"},
{slug:"intro-retail-merchandising", name:"Introduction to Retail & Merchandising", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Covers product placement, inventory control, customer experience, and sales techniques in a retail setting.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Retail-and-Merchandising.pdf"},
{slug:"intro-supply-chain-management", name:"Introduction to Supply Chain Management", level:"High School", type:"Objective Test", grades:"9th & 10th Grade Only", desc:"Introduces logistics, inventory control, procurement, and distribution — how goods and information flow through a supply chain.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Introduction-to-Supply-Chain-Management.pdf"},
{slug:"journalism", name:"Journalism", level:"High School", type:"Objective Test", desc:"Covers journalistic principles, media ethics, news writing, reporting, and editing in a digital-first news economy.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Journalism.pdf"},
{slug:"networking-infrastructures", name:"Networking Infrastructures", level:"High School", type:"Objective Test", desc:"Covers network design, protocols, hardware, and security — the backbone of reliable connectivity in any workplace.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Networking-Infrastructures.pdf"},
{slug:"organizational-leadership", name:"Organizational Leadership", level:"High School", type:"Objective Test", desc:"Covers leadership styles, team management, motivation, and ethical decision-making in a business context.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Organizational-Leadership.pdf"},
{slug:"personal-finance", name:"Personal Finance", level:"High School", type:"Objective Test", desc:"Covers budgeting, saving, credit, investing, and the everyday decisions that build lifelong financial wellness.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Personal-Finance.pdf"},
{slug:"project-management", name:"Project Management", level:"High School", type:"Objective Test", desc:"Covers planning, scheduling, budgeting, risk management, and team coordination needed to lead a project from start to finish.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Project-Management.pdf"},
{slug:"public-administration-management", name:"Public Administration & Management", level:"High School", type:"Objective Test", desc:"Explores how government functions in society — public policy, organizational structure, budgeting, and political-economic systems.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Public-Administration-and-Management.pdf"},
{slug:"real-estate", name:"Real Estate", level:"High School", type:"Objective Test", desc:"Covers property law, real estate finance, market analysis, sales strategy, and ethical practice in the real estate industry.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Real-Estate.pdf", chapterEvent:true},
{slug:"retail-management", name:"Retail Management", level:"High School", type:"Objective Test", desc:"Covers inventory control, sales technique, merchandising, and product mix — the core operations behind running a retail business.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Retail-Management.pdf"},
{slug:"securities-and-investments", name:"Securities & Investments", level:"High School", type:"Objective Test", desc:"Covers stocks, bonds, mutual funds, portfolio management, and risk analysis for members exploring investing.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Securities-and-Investments.pdf"},

// ===== HIGH SCHOOL — ROLE PLAY =====
{slug:"banking-financial-systems", name:"Banking & Financial Systems", level:"High School", type:"Role Play", desc:"Pairs a written test with a role-play scenario on how financial institutions operate — banking services, regulatory compliance, and financial decision-making.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Banking-and-Financial-Systems.pdf"},
{slug:"business-management", name:"Business Management", level:"High School", type:"Role Play", desc:"Tests core management principles through a written exam plus a live scenario covering planning, organizing, leading, and decision-making.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Business-Management.pdf", chapterEvent:true},
{slug:"customer-service", name:"Customer Service", level:"High School", type:"Role Play", desc:"Tests the ability to deliver excellent service — answering inquiries, resolving issues, and creating a positive customer experience under pressure.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Customer-Service.pdf"},
{slug:"entrepreneurship", name:"Entrepreneurship", level:"High School", type:"Role Play", desc:"Applies entrepreneurial concepts — business planning, innovation, risk management, and strategic decision-making — to a live scenario.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Entrepreneurship.pdf"},
{slug:"hospitality-event-management", name:"Hospitality & Event Management", level:"High School", type:"Role Play", desc:"Covers customer service, operations, logistics, and marketing within the hospitality and event planning industry.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Hospitality-and-Event-Management.pdf"},
{slug:"international-business", name:"International Business", level:"High School", type:"Role Play", desc:"Explores international trade, cultural awareness, global marketing, and economic systems across borders.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/International-Business.pdf"},
{slug:"management-information-systems", name:"Management Information Systems", level:"High School", type:"Role Play", desc:"Analyzes a small business's tech environment and asks competitors to recommend effective information-system solutions.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Management-Information-Systems.pdf"},
{slug:"marketing", name:"Marketing", level:"High School", type:"Role Play", desc:"Covers market research, branding, promotion, and customer engagement through a written test and a live business scenario.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Marketing.pdf"},
{slug:"network-design", name:"Network Design", level:"High School", type:"Role Play", desc:"Tests the ability to design, implement, and troubleshoot network solutions that meet a business's needs.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Network-Design.pdf"},
{slug:"parliamentary-procedure", name:"Parliamentary Procedure", level:"High School", type:"Role Play", desc:"A team event applying parliamentary law through simulated meeting activities — motions, debate, and voting in real time.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Parliamentary-Procedure.pdf"},
{slug:"sports-entertainment-management", name:"Sports & Entertainment Management", level:"High School", type:"Role Play", desc:"Covers the business side of sports and entertainment — marketing, event planning, sponsorship, and financial management — through test and scenario.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Sports-and-Entertainment-Management.pdf", chapterEvent:true},
{slug:"technology-support-services", name:"Technology Support & Services", level:"High School", type:"Role Play", desc:"Tests help desk and IT support knowledge, applying problem-solving and customer-service skills to real tech support issues.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Technology-Support-and-Services.pdf"},

// ===== HIGH SCHOOL — PRESENTATION =====
{slug:"broadcast-journalism", name:"Broadcast Journalism", level:"High School", type:"Presentation", desc:"Members research, script, and produce a professional news segment, then deliver it live to a panel of judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Broadcast-Journalism.pdf"},
{slug:"business-ethics", name:"Business Ethics", level:"High School", type:"Presentation", desc:"Analyzes and presents solutions to real ethical dilemmas businesses face, covering integrity and corporate responsibility.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Business-Ethics.pdf"},
{slug:"business-plan", name:"Business Plan", level:"High School", type:"Presentation", desc:"Develop and present a full plan for launching a new business, including a written report and a live pitch to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Business-Plan.pdf"},
{slug:"career-portfolio", name:"Career Portfolio", level:"High School", type:"Presentation", desc:"Showcases your accomplishments, skills, and career goals in a professional portfolio presented to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Career-Portfolio.pdf"},
{slug:"coding-programming", name:"Coding & Programming", level:"High School", type:"Presentation", desc:"Design and build a standalone application solving a specific problem, then present the finished program to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Coding-and-Programming.pdf"},
{slug:"computer-game-simulation-programming", name:"Computer Game & Simulation Programming", level:"High School", type:"Presentation", desc:"Design and develop an interactive game or simulation on a given topic, blending creativity with technical problem-solving.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Computer-Game-Simulation-Programming.pdf"},
{slug:"data-analysis", name:"Data Analysis", level:"High School", type:"Presentation", desc:"Examine a data set to uncover insights, then present findings and visualizations that support clear conclusions.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Data-Analysis.pdf"},
{slug:"digital-animation", name:"Digital Animation", level:"High School", type:"Presentation", desc:"Design and present an original animated video, demonstrating storytelling and animation fundamentals.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Digital-Animation.pdf"},
{slug:"digital-video-production", name:"Digital Video Production", level:"High School", type:"Presentation", desc:"Plan, produce, and present a compelling video tailored to a specific audience — video as a communication and promotion tool.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Digital-Video-Production.pdf"},
{slug:"event-planning", name:"Event Planning", level:"High School", type:"Presentation", desc:"Develop and present a plan for a real event, covering organization, budgeting, promotion, and logistics.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Event-Planning.pdf"},
{slug:"financial-planning", name:"Financial Planning", level:"High School", type:"Presentation", desc:"Analyze a family's financial scenario and present a strategy covering budgeting, saving, investing, and debt management.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Financial-Planning.pdf"},
{slug:"financial-statement-analysis", name:"Financial Statement Analysis", level:"High School", type:"Presentation", desc:"Interpret and evaluate financial statements on a given topic, then present findings and recommendations to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Financial-Statement-Analysis.pdf"},
{slug:"future-business-educator", name:"Future Business Educator", level:"High School", type:"Presentation", desc:"Explore a career in business education through a pre-judged lesson plan and a live teaching-focused presentation.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Future-Business-Educator.pdf"},
{slug:"future-business-leader", name:"Future Business Leader", level:"High School", type:"Presentation", desc:"FBLA's premier event recognizing all-around leadership, business knowledge, and active chapter involvement through pre-judged materials, a test, and an interview.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Future-Business-Leader.pdf"},
{slug:"graphic-design", name:"Graphic Design", level:"High School", type:"Presentation", desc:"Develop original visual content and present the design process, showing off design principles and software skills.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Graphic-Design.pdf"},
{slug:"impromptu-speaking", name:"Impromptu Speaking", level:"High School", type:"Presentation", desc:"Deliver a well-organized speech on a topic revealed on the spot — a real test of quick thinking and composure.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Impromptu-Speaking.pdf"},
{slug:"intro-business-presentation", name:"Introduction to Business Presentation", level:"High School", type:"Presentation", grades:"9th & 10th Grade Only", desc:"Develop and deliver a business-focused presentation using slides as a visual aid, geared toward underclassmen.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Introduction-to-Business-Presentation.pdf"},
{slug:"intro-programming", name:"Introduction to Programming", level:"High School", type:"Presentation", grades:"9th & 10th Grade Only", desc:"Design a basic computer program on a given topic and present it, an entry point into Coding & Programming.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Introduction-to-Programming.pdf"},
{slug:"intro-public-speaking", name:"Introduction to Public Speaking", level:"High School", type:"Presentation", grades:"9th & 10th Grade Only", desc:"Develop and deliver a speech on a designated topic — a confidence-building entry point into public speaking events.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Introduction-to-Public-Speaking.pdf"},
{slug:"intro-social-media-strategy", name:"Introduction to Social Media Strategy", level:"High School", type:"Presentation", grades:"9th & 10th Grade Only", desc:"Develop a marketing strategy centered on a single social platform, covering audience engagement and content creation.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Introduction-to-Social-Media-Strategy.pdf"},
{slug:"job-interview", name:"Job Interview", level:"High School", type:"Presentation", desc:"Build a résumé and cover letter, then complete a live interview evaluating communication, poise, and workplace readiness.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Job-Interview.pdf"},
{slug:"mobile-application-development", name:"Mobile Application Development", level:"High School", type:"Presentation", desc:"Design and build a functional mobile app on a given topic, presenting UI design and technical problem-solving to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Mobile-Application-Development.pdf"},
{slug:"public-service-announcement", name:"Public Service Announcement", level:"High School", type:"Presentation", desc:"Create a 60-second PSA video raising awareness about an issue, then present and explain the creative process to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Public-Service-Announcement.pdf"},
{slug:"public-speaking", name:"Public Speaking", level:"High School", type:"Presentation", desc:"Develop and deliver a well-structured speech on a designated topic to build confidence and persuasive communication.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Public-Speaking.pdf", chapterEvent:true},
{slug:"sales-presentation", name:"Sales Presentation", level:"High School", type:"Presentation", desc:"Deliver an interactive sales pitch for a product or service of your choice, showing off persuasive selling technique.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Sales-Presentation.pdf"},
{slug:"social-media-strategies", name:"Social Media Strategies", level:"High School", type:"Presentation", desc:"Develop a full marketing campaign across multiple social platforms, presenting audience engagement and content strategy.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Social-Media-Strategies.pdf"},
{slug:"supply-chain-management", name:"Supply Chain Management", level:"High School", type:"Presentation", desc:"Present knowledge of logistics, procurement, inventory control, and distribution strategy that keeps businesses running.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Supply-Chain-Management.pdf"},
{slug:"visual-design", name:"Visual Design", level:"High School", type:"Presentation", desc:"Develop original visual content and present the design principles and creative process behind it.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Visual-Design.pdf"},
{slug:"website-coding-development", name:"Website Coding & Development", level:"High School", type:"Presentation", desc:"Build a website with a focus on backend coding and functionality, presenting the finished site to judges.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Website-Coding-and-Development.pdf"},
{slug:"website-design", name:"Website Design", level:"High School", type:"Presentation", desc:"Create a visually engaging, user-friendly website emphasizing front-end layout, navigation, and user experience.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Website-Design.pdf"},

// ===== HIGH SCHOOL — PRODUCTION / CHAPTER =====
{slug:"computer-applications", name:"Computer Applications", level:"High School", type:"Production", desc:"Tests proficiency with word processing, spreadsheets, and presentation software through real business production tasks.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Production%20Events/Computer-Applications.pdf"},
{slug:"community-service-project", name:"Community Service Project", level:"High School", type:"Chapter Event", desc:"Showcases a chapter service initiative addressing a need in the school or local community, judged on report and live presentation.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Chapter%20Events/Community-Service-Project.pdf"},
{slug:"local-chapter-annual-business-report", name:"Local Chapter Annual Business Report", level:"High School", type:"Chapter Event", desc:"Documents and presents the chapter's Program of Work for the year — goals, activities, and overall impact.", pdf:"https://connect.fbla.org/headquarters/files/High%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Chapter%20Events/Local-Chapter-Annual-Business-Report.pdf"},

// ===== MIDDLE SCHOOL — OBJECTIVE TESTS =====
{slug:"ms-business-etiquette", name:"Business Etiquette", level:"Middle School", type:"Objective Test", desc:"Tests knowledge of professional behavior, appearance, communication, and conduct in workplace and social settings.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Business-Etiquette.pdf"},
{slug:"ms-career-exploration", name:"Career Exploration", level:"Middle School", type:"Objective Test", desc:"Tests knowledge of various career fields, encouraging members to evaluate options and start planning for the future.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Career-Exploration.pdf"},
{slug:"ms-digital-citizenship", name:"Digital Citizenship", level:"Middle School", type:"Objective Test", desc:"Tests safe, ethical, and responsible behavior online — the skills to navigate the internet with confidence and integrity.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Digital-Citizenship.pdf"},
{slug:"exploring-accounting-finance", name:"Exploring Accounting & Finance", level:"Middle School", type:"Objective Test", desc:"An introduction to foundational accounting and finance concepts for members curious about the field.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Accounting-and-Finance.pdf"},
{slug:"exploring-agribusiness", name:"Exploring Agribusiness", level:"Middle School", type:"Objective Test", desc:"Introduces the world of agribusiness at the intersection of agriculture, economics, and entrepreneurship.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Agribusiness.pdf"},
{slug:"exploring-business-communication", name:"Exploring Business Communication", level:"Middle School", type:"Objective Test", desc:"Introduces the principles of effective communication inside and outside a business setting.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Business-Communication.pdf"},
{slug:"exploring-business-concepts", name:"Exploring Business Concepts", level:"Middle School", type:"Objective Test", desc:"Introduces key business functions — management, marketing, finance, and operations — for beginners.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Business-Concepts.pdf"},
{slug:"exploring-computer-science", name:"Exploring Computer Science", level:"Middle School", type:"Objective Test", desc:"Introduces hardware, software, algorithms, and computational thinking at a middle-school level.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Computer-Science.pdf"},
{slug:"exploring-economics", name:"Exploring Economics", level:"Middle School", type:"Objective Test", desc:"Introduces supply and demand, market structures, and the role of government in the economy.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Economics.pdf"},
{slug:"exploring-fbla", name:"Exploring FBLA", level:"Middle School", type:"Objective Test", desc:"Covers FBLA's history, structure, programs, leadership, and mission — a solid intro to the organization.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-FBLA.pdf"},
{slug:"exploring-leadership", name:"Exploring Leadership", level:"Middle School", type:"Objective Test", desc:"Introduces core leadership principles — how effective leaders align teams and guide others toward shared goals.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Leadership.pdf"},
{slug:"exploring-marketing-concepts", name:"Exploring Marketing Concepts", level:"Middle School", type:"Objective Test", desc:"Introduces market research, promotion, branding, and the basics of selling products and services.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Marketing-Concepts.pdf"},
{slug:"exploring-parliamentary-procedure", name:"Exploring Parliamentary Procedure", level:"Middle School", type:"Objective Test", desc:"Introduces meeting structure and orderly decision-making — motions, debate, and voting procedures.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Parliamentary-Procedure.pdf"},
{slug:"exploring-personal-finance", name:"Exploring Personal Finance", level:"Middle School", type:"Objective Test", desc:"Introduces budgeting, saving, credit, investing, and everyday financial decision-making.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Personal-Finance.pdf"},
{slug:"exploring-professionalism", name:"Exploring Professionalism", level:"Middle School", type:"Objective Test", desc:"Introduces expectations around professional behavior, appearance, communication, and conduct.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Professionalism.pdf"},
{slug:"exploring-technology", name:"Exploring Technology", level:"Middle School", type:"Objective Test", desc:"Introduces digital tools, emerging technologies, cybersecurity basics, and technology's role in everyday life.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Exploring-Technology.pdf"},
{slug:"ms-fbla-concepts", name:"FBLA Concepts", level:"Middle School", type:"Objective Test", desc:"A knowledge test covering core FBLA organizational concepts.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/FBLA-Concepts.pdf"},
{slug:"ms-financial-literacy", name:"Financial Literacy", level:"Middle School", type:"Objective Test", desc:"Tests foundational financial literacy knowledge for middle schoolers.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Financial-Literacy.pdf"},
{slug:"ms-interpersonal-communication", name:"Interpersonal Communication", level:"Middle School", type:"Objective Test", desc:"Explores how people exchange messages and ideas — verbal and nonverbal communication, active listening, and relationship-building.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Interpersonal-Communication.pdf"},
{slug:"ms-learning-strategies", name:"Learning Strategies", level:"Middle School", type:"Objective Test", desc:"Tests strategies and study skills that help students learn and retain information more effectively.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Learning-Strategies.pdf"},
{slug:"ms-running-effective-meeting", name:"Running an Effective Meeting", level:"Middle School", type:"Objective Test", desc:"Tests knowledge of how to plan and run a productive, well-organized meeting.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Objective%20Tests/Running-an-Effective-Meeting.pdf"},

// ===== MIDDLE SCHOOL — ROLE PLAY =====
{slug:"ms-critical-thinking", name:"Critical Thinking", level:"Middle School", type:"Role Play", desc:"Gives members the chance to think on their feet and present a solution to a problem in a live role-play scenario.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Critical-Thinking.pdf"},
{slug:"exploring-customer-service", name:"Exploring Customer Service", level:"Middle School", type:"Role Play", desc:"Tests quick, effective response to a customer-related scenario — problem-solving, communication, and interpersonal skill.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Exploring-Customer-Service.pdf"},
{slug:"exploring-management-entrepreneurship", name:"Exploring Management & Entrepreneurship", level:"Middle School", type:"Role Play", desc:"Presents a real-world business management or entrepreneurship scenario, testing leadership and decision-making on the spot.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Role%20Play%20Events/Exploring-Management-and-Entrepreneurship.pdf"},

// ===== MIDDLE SCHOOL — PRESENTATION =====
{slug:"ms-career-research", name:"Career Research", level:"Middle School", type:"Presentation", desc:"Research and present findings on a career of personal interest — education needed, responsibilities, and outlook.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Career-Research.pdf"},
{slug:"ms-elevator-speech", name:"Elevator Speech", level:"Middle School", type:"Presentation", desc:"Deliver a short, focused pitch on a given topic — the classic \"elevator speech\" communication skill.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Elevator-Speech.pdf"},
{slug:"exploring-animation", name:"Exploring Animation", level:"Middle School", type:"Presentation", desc:"Design and present an original animated video, applying fundamental animation principles.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Animation.pdf"},
{slug:"exploring-business-ethics", name:"Exploring Business Ethics", level:"Middle School", type:"Presentation", desc:"Explores standards of right and wrong conduct and ethical decision-making in business, at an introductory level.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Business-Ethics.pdf"},
{slug:"exploring-business-issues", name:"Exploring Business Issues", level:"Middle School", type:"Presentation", desc:"Research a current business topic and present an analysis and proposed solution — critical thinking and communication.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Business-Issues.pdf"},
{slug:"exploring-coding-programming", name:"Exploring Coding & Programming", level:"Middle School", type:"Presentation", desc:"Develop a program based on a given topic and demonstrate the finished product to judges.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Coding-and-Programming.pdf"},
{slug:"exploring-digital-video-production", name:"Exploring Digital Video Production", level:"Middle School", type:"Presentation", desc:"Plan, produce, and present a compelling video for a specific audience, showcasing storytelling and technical skill.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Digital-Video-Production.pdf"},
{slug:"exploring-marketing-strategies", name:"Exploring Marketing Strategies", level:"Middle School", type:"Presentation", desc:"Develop and present a marketing strategy for a new, realistic product or service.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Marketing-Strategies.pdf"},
{slug:"exploring-public-speaking", name:"Exploring Public Speaking", level:"Middle School", type:"Presentation", desc:"Develop and deliver a speech on a designated topic to build confidence and communication skill.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Public-Speaking.pdf"},
{slug:"exploring-website-design", name:"Exploring Website Design", level:"Middle School", type:"Presentation", desc:"Design, develop, and present a website on a given topic — an intro to web design fundamentals.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Exploring-Website-Design.pdf"},
{slug:"ms-fbla-mission-pledge", name:"FBLA Mission & Pledge", level:"Middle School", type:"Presentation", desc:"A speech event centered on FBLA's mission and pledge.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/FBLA-Mission--Pledge.pdf"},
{slug:"ms-marketing-mix-challenge", name:"Marketing Mix Challenge", level:"Middle School", type:"Presentation", desc:"A presentation event challenging members to apply the marketing mix (product, price, place, promotion) to a topic.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Marketing-Mix-Challenge.pdf"},
{slug:"ms-multimedia-website-development", name:"Multimedia & Website Development", level:"Middle School", type:"Presentation", desc:"Build and present a multimedia or website project on a given topic, combining creativity with technical skill.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Multimedia--Website-Development.pdf"},
{slug:"ms-video-game-challenge", name:"Video Game Challenge", level:"Middle School", type:"Presentation", desc:"Design and present an original video game concept on a given topic.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Presentation%20Events/Video-Game-Challenge.pdf"},

// ===== MIDDLE SCHOOL — PRODUCTION / CHAPTER =====
{slug:"ms-slide-deck-applications", name:"Slide Deck Applications", level:"Middle School", type:"Production", desc:"Tests the ability to turn information into effective, professional slide decks through a production test.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Production%20Events/Slide-Deck-Applications.pdf"},
{slug:"ms-spreadsheet-applications", name:"Spreadsheet Applications", level:"Middle School", type:"Production", desc:"Tests organizing, analyzing, and presenting data using spreadsheet software — formulas, charts, and data management.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Production%20Events/Spreadsheet-Applications.pdf"},
{slug:"ms-word-processing", name:"Word Processing", level:"Middle School", type:"Production", desc:"Tests proficiency creating, editing, formatting, and producing professional documents with word processing software.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Production%20Events/Word-Processing.pdf"},
{slug:"ms-annual-chapter-activities-presentation", name:"Annual Chapter Activities Presentation", level:"Middle School", type:"Chapter Event", desc:"Showcases the chapter's program of work for the year through a live team presentation.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Chapter%20Events/Annual-Chapter-Activities-Presentation.pdf"},
{slug:"ms-community-service-presentation", name:"Community Service Presentation", level:"Middle School", type:"Chapter Event", desc:"Showcases a chapter service project benefiting the school or community, judged on goals, execution, and impact.", pdf:"https://connect.fbla.org/headquarters/files/Middle%20School%20Competitive%20Events%20Resources/Individual%20Guidelines/Chapter%20Events/Community-Service-Presentation.pdf"},
];
